version: '3.8'

services:
  zephyr-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: zephyr-dev
    volumes:
      - .:/workdir:cached
      - zephyr_build:/workdir/build
      - zephyr_cache:/home/user/.cache
    working_dir: /workdir
    user: user
    stdin_open: true
    tty: true
    privileged: true  # Needed for hardware debugging
    devices:
      - /dev/bus/usb:/dev/bus/usb  # USB device access for flashing
    ports:
      - "2331:2331"    # J-Link GDB Server
      - "19021:19021"  # J-Link RTT Viewer
    environment:
      - DISPLAY=${DISPLAY:-}
      - ZEPHYR_BASE=/zephyrproject/zephyr
      - ZEPHYR_TOOLCHAIN_VARIANT=zephyr
      - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
    command: /bin/bash

volumes:
  zephyr_build:
    driver: local
  zephyr_cache:
    driver: local