name: Release Dev Container Features

on:
  push:
    branches:
      - 'release/*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  release-features:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') && contains(github.ref, 'v') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract version from branch name or input
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            VERSION=$(echo $BRANCH_NAME | grep -oP 'v\K[0-9]+\.[0-9]+\.[0-9]+')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update feature version in JSON
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.version.outputs.version }}"/' zephyr-dev-features/src/zephyr-dev/devcontainer-feature.json

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Dev Container Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./zephyr-dev-features/src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          NAMESPACE: jaybuckeye06

      - name: Create tgz package
        run: |
          mkdir -p dist
          tar -czf dist/zephyr-dev-features-${{ steps.version.outputs.version }}.tgz -C zephyr-dev-features .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: "zephyr-dev-features ${{ steps.version.outputs.tag }}"
          files: dist/zephyr-dev-features-${{ steps.version.outputs.version }}.tgz
          generate_release_notes: true
          prerelease: false